### ISSUE TITLE
sys.exit() before completion

### ISSUE THREAD

**Issue by skylover007** [Slyyxp/BugsPy#8]
Thank you very much for your active response each time.

When I try to download an [album](https://music.bugs.co.kr/artist/1285) as an artist, I cannot download it.  
[16.29.15.log](https://github.com/Slyyxp/BugsPy/files/5177773/16.29.15.log)

![image](https://user-images.githubusercontent.com/35911123/92301313-67459380-ef95-11ea-8048-19c6d518b7b7.png)
![image](https://user-images.githubusercontent.com/35911123/92301325-8e03ca00-ef95-11ea-8f0e-6b9e8fa4d679.png)

**Comment by Slyyxp** [comment]
Closed with https://github.com/Slyyxp/BugsPy/commit/129a4a951ce0198fe6c59f713a06d7e876c7729a
Revised with https://github.com/Slyyxp/BugsPy/commit/f4daaec86b9c8892b836c1efb1c44ff08f60367f

This will no longer sys.exit(). However this album will still not be downloaded, the album may be listed under releases but this script has marked it as a contribution. Rightfully so I'd say based on the contents and credits.

Due to the API not returning whether they have personally listed something as a contribution the script will decide based upon if the artist id attached to the album is the same as the artist id of the page being downloaded.

```python
		contribution_status = utils.contribution_check(artist_id, album['artist_id'])
		if contribution_status:
			if config.prefs['include_contributions']:
				album_rip(album['album_id'])
			else:
				logger_bugs.info("{} - {} has been marked as a contribution and skipped.".format(album['title'].strip()))
		else:
			album_rip(album['album_id'])
```
  
```python
def contribution_check(artist_id_provided, artist_id_api):
	if int(artist_id_provided) == int(artist_id_api):
		return False
	else:
		return True
```
