### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by skylover007** [Slyyxp/BugsPy#9]
Hi, Slyy~

When I tried to download this [artist](https://music.bugs.co.kr/artist/80013575)’s album, the following error occurred and the download could not be completed

If the problem cannot be fixed, please let the downloader skip the album and continue to the next album

Thank you very much

[17.58.14.log](https://github.com/Slyyxp/BugsPy/files/5249548/17.58.14.log)

![2020-09-19_175857](https://user-images.githubusercontent.com/35911123/93664467-d648df00-faa1-11ea-9f33-f67b5c2c5a42.png)

**Comment by Slyyxp** [comment]
I'm actually not entirely sure what the cause of this issue is. My Windows 10 device can pass this album fine in both an artist batch and single album download.

My first thought was the long directory name but this does not reach the character limit.

I have pushed a new commit which should solve the bloated directory name, this will likely not solve your issue however I want you to pull it and try anyway before proceeding.

https://github.com/Slyyxp/BugsPy/commit/3dc4d84c97c2d6660185b3429a755f396a54f928

**Comment by skylover007** [comment]
Thank you very much, the problem has been solved
This time the artist’s name has been changed to various artists, and the download was successful

Thanks again !

![image](https://user-images.githubusercontent.com/35911123/93707632-e4126900-fb62-11ea-8b7c-5c04eae3e2a1.png)
